# Generated by Django 4.2.15 on 2024-09-22 20:43

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=100)),
                ('discipline_icon', models.ImageField(blank=True, upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDisciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')])),
                ('profile_discipline_order', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['stage_name']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=account.models.user_directory_path),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['stage_name'], name='account_pro_stage_n_0529a2_idx'),
        ),
        migrations.AddField(
            model_name='profiledisciplines',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_profiles', to='account.profile'),
        ),
        migrations.AddField(
            model_name='profiledisciplines',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_disciplines', to='account.profile'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='parent_discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_discipline', to='account.discipline'),
        ),
    ]
