# Generated by Django 4.2.15 on 2024-10-06 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_datetime', models.DateTimeField()),
                ('event_location', models.CharField(max_length=100)),
                ('event_website', models.TextField(blank=True, null=True)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('event_private_description', models.TextField(blank=True, null=True)),
                ('event_picture', models.ImageField(blank=True, upload_to='event_pictures/')),
                ('event_organiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organiser_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_name'],
                'indexes': [models.Index(fields=['event_name'], name='events_even_event_n_0bdbb0_idx')],
            },
        ),
    ]
